### ISSUE TITLE
Filter by sponsor has missing names

### ISSUE THREAD

**Issue by derekeder** [datamade/nyc-council-councilmatic#105]
1. Go to the Legislation page: https://laws.council.nyc.gov/search/
2. Click filter by sponsor
3. The list of sponsors has redundant and missing names

Notably:
* missing Margaret Chin (district 1)
* District 2
* District 7
* District 8

Not seeing this issue on the staging site: https://nyc-council-staging.datamade.us/search/

**Comment by reginafcompton** [comment]
I re-ran `import_data` and I rebuilt the index. This problem persists. The numbers seem odd, however:

The import: 36679 bills
Rebuild index: 32123 bills

**Comment by reginafcompton** [comment]
Here's what I can glean, thus far:

We prepare a bill's sponsorships like so: https://github.com/datamade/django-councilmatic/blob/master/councilmatic_core/haystack_indexes.py#L47

I can see those sponsorships when I [search the Solr interface](http://127.0.0.1:8983/solr/#/nyc-council-councilmatic/query)....entering a bill sponsored by M. Chin in the "q" field (e.g., "Introduction 1062-2016").

However, the [`facets` dict (extra['facets']['fields']['sponsorships']) in the CouncilmaticFacetedSearchField](https://github.com/datamade/django-councilmatic/blob/master/councilmatic_core/views.py#L49) does not contain the all the sponsorships we expect - that is, it's missing M. Chin and others. This dict is important, since its what we show in the template: https://github.com/datamade/django-councilmatic/blob/master/councilmatic_core/templates/search/search.html#L88

Why is this dict incomplete? how is it getting generated?
