### ISSUE TITLE
Dockerizing solr: update

### ISSUE THREAD

**Issue by reginafcompton** [datamade/nyc-council-councilmatic#40]
**A short summary of the Docker saga**

We initially installed Docker using the instructions [provided for Linux machines](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-using-the-repository). By default, we got docker-compose, version 1.8.0. This caused a problem: we could only use “older” versions of docker-compose.yml. So, we installed docker-compose in a virtual env, using `pip install`.

Still, docker-compose (within a virtualenv) could not communicate with Docker, due to permissions errors. 

Then, we did the following:

* uninstall docker-compose in the virtualenv
* install version 1.8.0 using the instructions here:https://docs.docker.com/compose/install/#install-compose
* downgrade the docker-compose.yml file to version “2”

This error still persists:
```
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?
If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable
```
The response from dnephin on Mar 11, 2016 gives some suggestions, one having to do with permissions: https://github.com/docker/compose/issues/1214

Permissions? Just use `sudo`! As the Ubuntu user, visit the `nyc-council-councilmatic` directory....and witness the following:

<img width="756" alt="screen shot 2017-11-29 at 2 09 06 pm" src="https://user-images.githubusercontent.com/13078679/33397148-5f1937ae-d510-11e7-8106-cbecb13589fe.png">

We are CLOSE, but need to rethink the configuration of Docker compose.

**Comment by reginafcompton** [comment]
For the staging server, we'll deploy Solr the "old fashioned" way.

**Comment by fgregg** [comment]
Reading through the notes, it seems like some of the difficulties might be due to cutting against the grain. The dream of docker is that the image that you build locally is the same version you use remotely. 

Building the image both locally and remotely undercuts that.

The more-trodden path seems to build an image locally, send that image to a container registry, like Amazon's http://docs.aws.amazon.com/AmazonECR/latest/userguide/ECR_GetStarted.html
