### ISSUE TITLE
Searchin for Resolution 815-2015 does not return Resolution 815-2015

### ISSUE THREAD

**Issue by fgregg** [datamade/nyc-council-councilmatic#88]
We encourage the user to search for Resolution 815-2015 but do not return this result. This is likely because when we search we are not automatically sorting by relevance. We should sort by relevance when people enter in search terms.

**Comment by jeancochrane** [comment]
One interesting complication to sorting by relevance that we've found in the process of working on https://github.com/datamade/nyc-council-councilmatic/pull/120:

When you're looking for a specific bill, sorting by relevance is usually the only way to find it. As I see it, his is the primary problem raised in this issue. e.g. searching for `Resolution 815-2014` returns the wrong result when `Date` is the ordering:

![resolution-815-date](https://user-images.githubusercontent.com/14170650/35290150-f500b65e-002e-11e8-848b-cf93301a3e15.png)

Using `Resolution` to order it, however, returns the right bill immediately:

![resolution-815-relevance](https://user-images.githubusercontent.com/14170650/35290164-fc96a572-002e-11e8-9bd3-d2cb3b730a86.png)

However, when searching for broad keywords like `Taxi`, **the opposite is true!** In these cases, sorting by `Date` shows the freshest bills on that topic:

![taxi-date](https://user-images.githubusercontent.com/14170650/35290192-1171a28a-002f-11e8-9cc8-b1245f89ac75.png)

While sorting by `Relevance` shows bills that may in fact have many mentions of `Taxi` in their index, but are from so long ago that they probably aren't relevant to a casual user:

![tax-relevance](https://user-images.githubusercontent.com/14170650/35290232-2cb1122e-002f-11e8-81ae-6ebe6c0dfe48.png)

I think the issue here is getting at **defining what relevance means to different users**. Casual users of the site may find recent bills to be more relevant; power users may want to find specific bills, and so find "exactness and number of word matches" to be more relevant.

A couple of ways forward:

- Move to defaulting to search by relevance, and accept that casual users looking for broad keywords will find worse results
- Continue to default search by date, and add a small call-out by the results explaining that "if you aren't finding a specific bill that you're looking for, try searching by relevance"
- Continue to default search by date, and add a "FAQ" section that explains how to search

**Comment by fgregg** [comment]
Boy this is a tough one since the "power users" are actually our clients. 

So, one way that we have tried to address this in the past is through boosting. 

http://django-haystack.readthedocs.io/en/master/boost.html

Can we boost "freshness" so that we a "relevance" search returns pretty good results for the Taxi case and for the Resolution 815-2015 case?

**Comment by fgregg** [comment]
https://github.com/datamade/chi-councilmatic/blob/47c5e7d26da1cc6012e0ae7831f499e8be35405a/chicago/search_indexes.py#L21-L26
